{% set name = "rockpool" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b2e28581eff8ffbe65bb0b7423d625dd4a7c3da19b44f868ac03817face2e5c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - numpy
    - python >=3.6

test:
  imports:

about:
  home: https://gitlab.com/synsense/rockpool
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: Python package for developing, simulating and training spiking neural networks, and deploying on Neuromorphic hardware

  description: |
    Rockpool is a Python package for working with dynamical neural network architectures, particularly for designing event-driven networks for Neuromorphic computing hardware. Rockpool provides a convenient interface for designing, training and evaluating recurrent networks, which can operate both with continuous-time dynamics and event-driven dynamics.
    Rockpool is an open-source project managed by SynSense
  doc_url: https://rockpool.ai
  dev_url: https://gitlab.com/synsense/rockpool

extra:
  recipe-maintainers:
    - DylanMuir
    - ssinhaleite
