{% set name = "rockpool" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7cab1ac7656fe6c4cc79aed080a827c162df19c2e70d3132b29917df68938b9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - numpy
    - python >=3.6

test:
  imports:

about:
  home: https://gitlab.com/synsense/rockpool
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: Python package for developing, simulating and training spiking neural networks, and deploying on Neuromorphic hardware

  description: |
    Rockpool is a Python package for working with dynamical neural network architectures, particularly for designing event-driven networks for Neuromorphic computing hardware. Rockpool provides a convenient interface for designing, training and evaluating recurrent networks, which can operate both with continuous-time dynamics and event-driven dynamics.
    Rockpool is an open-source project managed by SynSense
  doc_url: https://rockpool.ai
  dev_url: https://gitlab.com/synsense/rockpool

extra:
  recipe-maintainers:
    - DylanMuir
